spring:
  devtools:
    restart:
      additional-paths: resources/**,static/**,templates/**
  http:
    encoding:
      charset: utf-8
      force: true
      enabled: true
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:mem:dbHtmlVue
    driver-class-name: org.h2.Driver
    username: root
    password: root
    platform: h2
    schema: classpath:db/schema.sql
    data: classpath:db/data.sql
    initialization-mode: always
  #h2数据库远程管理
  h2:
    console:
      #是否开启web显示
      enabled: true
        #路径
      path: /console
      settings:
        #是否可以远程web
        web-allow-others: true
        trace: true
server:
  tomcat:
    uri-encoding: UTF-8
  port: 8193

logging:
  file:
    name: /logs/htmlVue/htmlVue.log
    max-size: 500MB
  level:
    org.springframework.web: INFO